"""
NetCDF utility function to save a numpy array as a NetCDF file with projection and meta data.
"""

# pylint: disable=W0212, W0718,R0915,E1101,R0914,R0912

import datetime
import numpy as np
import hf_hydrodata as hf
import netCDF4
import pyproj
import dateutil


def generate_netcdf_file(
    data: np.ndarray, entry: dict, query_parameters: dict, filename: str
):
    """Generate a NetCDF file from numpy data array."""
    grid = entry.get("grid")
    grid_bounds = hf.gridded._get_grid_bounds(grid, query_parameters)
    variable = entry.get("variable")
    dataset = entry.get("dataset")
    temporal_resolution = entry.get("temporal_resolution")
    variable_row = hf.get_table_row("variable", id=variable)
    has_z = variable_row["has_z"].lower() == "true" if variable_row else False
    metadata = construct_metadata(entry, query_parameters)
    include_xy_coords = True

    if len(data.shape) == 4:
        # 3D plus time
        nz = data.shape[1]
        nx = data.shape[3]
        ny = data.shape[2]
    elif len(data.shape) == 3:
        # could be 2D plus time or 3D
        nz = data.shape[0]
        nx = data.shape[2]
        ny = data.shape[1]
    elif len(data.shape) == 2:
        # 2D without time
        nx = data.shape[1]
        ny = data.shape[0]
        nz = 0
    elif len(data.shape) == 1:
        # 1D data such as anomoly data
        nx = data.shape[0]
        ny = 0
        nz = 0
        include_xy_coords = False
    else:
        raise ValueError("Data shape has too many dimensions")

    # Use CLASSIC because this allows client to load streamed data from memory
    # The newer NETCDF4 relies on file positiong that requires to save into a file
    nc = netCDF4.Dataset(filename, "w", format="NETCDF3_CLASSIC")

    if not include_xy_coords:
        # This is one 1D so do not add x,y coords with CRS
        dimension_names = ["x"]
        nc.createDimension("x", nx)
    else:
        # This is 2D or 3D data with or without time dimension
        grid_data = hf.get_table_row("grid", id=grid)
        proj4_str = grid_data.get("crs")
        dx = float(grid_data.get("resolution_meters"))
        dy = float(grid_data.get("resolution_meters"))

        # Create x,y Dimensions
        x0 = float(grid_data.get("origin")[0])
        y0 = float(grid_data.get("origin")[1])
        if grid_bounds and len(grid_bounds) == 4:
            left_origin = x0 + grid_bounds[0] * dx
            bottom_origin = y0 + grid_bounds[1] * dx
        else:
            # If there no grid_bounds then the origin is the same as origin of the grid itself
            left_origin = x0
            bottom_origin = y0

        x = left_origin + (np.arange(nx) + 0.5) * dx
        y = bottom_origin + (np.arange(ny) + 0.5 * 0) * dy
        z = np.arange(nz)

        # -----------------------------
        # Create CF-compliant NetCDF
        # -----------------------------
        # Dimensions
        nc.createDimension("x", nx)
        nc.createDimension("y", ny)
        if has_z:
            nc.createDimension("z", nz)
        if temporal_resolution in ["daily", "hourly", "monthly", "weekly"]:
            nc.createDimension("time", None)
            dimension_names = ("time", "z", "y", "x") if has_z else ("time", "y", "x")
        else:
            dimension_names = ("z", "y", "x") if has_z else ("y", "x")
        create_time_variable(nc, data, temporal_resolution, query_parameters)

        # Coordinate variables

        if has_z:
            vz = nc.createVariable("z", "i4", ("z",))
        vy = nc.createVariable("y", "f8", ("y",))
        vx = nc.createVariable("x", "f8", ("x",))

        vx.standard_name = "projection_x_coordinate"
        vx.long_name = "x coordinate of projection"
        vx.units = "m"
        vx.axis = "X"
        vy.standard_name = "projection_y_coordinate"
        vy.long_name = "y coordinate of projection (northing)"
        vy.units = "m"
        vy.axis = "Y"
        vx[:] = x
        vy[:] = y
        if has_z:
            vz[:] = z

        # Grid mapping (CRS) variable
        # CF-compliant description of Lambert Conformal Conic (2SP)
        crs = nc.createVariable("crs", "i4")
        crs.grid_mapping_name = "lambert_conformal_conic"
        wkt = pyproj.CRS.from_proj4(proj4_str).to_wkt()
        crs.spatial_ref = wkt

    # Data variable
    var = nc.createVariable(variable, "f8", dimension_names, zlib=True, complevel=4)
    var.long_name = entry.get("variable")
    var[:] = data
    if include_xy_coords:
        var.units = f"{dx} meters"
        var.coordinates = " ".join(dimension_names)
        var.grid_mapping = "crs"
        nc.Conventions = "CF-1.9"

    # A few helpful global attributes
    nc.title = f"{variable} from dataset {dataset}"
    nc.source = "Generated by hf_hydrodata"

    # Add metadata attributes to the NC file
    for key, value in metadata.items():
        setattr(nc, key, value)

    nc.close()


def create_time_variable(
    nc: netCDF4.Dataset,
    data: np.ndarray,
    temporal_resolution: str,
    query_parameters: dict,
):
    """Create a time dimension variable in the NetCDF Dataset."""

    if temporal_resolution in ["daily", "hourly", "monthly", "weekly"]:
        date_start_str = get_date_start(query_parameters)
        if ":" in date_start_str:
            date_start = datetime.datetime.strptime(date_start_str, "%Y-%m-%d %H:%M:%S")
        else:
            date_start = datetime.datetime.strptime(date_start_str, "%Y-%m-%d")
        time_steps = data.shape[0]

        time_var = nc.createVariable("time", "f8", ("time",))
        time_var.standard_name = "time"
        time_var.units = "days since 1970-01-01 00:00:00"
        time_var.calendar = "standard"
        dates = []
        if temporal_resolution == "daily":
            delta = datetime.timedelta(days=1)
        elif temporal_resolution == "hourly":
            delta = datetime.timedelta(hours=1)
        elif temporal_resolution == "weekly":
            delta = datetime.timedelta(weeks=1)
        elif temporal_resolution == "monthly":
            delta = dateutil.relativedelta.relativedelta(months=1)
        dt = date_start
        for _ in range(0, time_steps):
            dates.append(dt)
            dt = dt + delta
        time_var[:] = netCDF4.date2num(
            dates, units=time_var.units, calendar=time_var.calendar
        )


def construct_metadata(entry: dict, query_parameters: dict):
    """
    Constructs metadata for the generated NetCDF file from the entry and query_parameters.

    Parameters
    ----------
    entry : dict
        dictionary containg the data catalog entry.
    query_parameters : dict
        dictionary containg all query parameters in the request.

    Returns
    -------
    metadata : dict
        The metadata of the requested data for use in generated NetCDF file.
    """

    required_fields = [
        "dataset",
        "variable",
        "dataset_var",
        "temporal_resolution",
        "units",
        "aggregation",
        "grid",
        "documentation_notes",
        "description",
        "paper_dois",
        "dataset_dois",
        "dataset_start_date",
        "dataset_dnd_Date",
        "time_zone",
        "documentation_link",
    ]
    metadata = {
        key: value
        for key, value in entry.row_values.items()
        if key in required_fields and value
    }

    date_start = get_date_start(query_parameters)
    date_end = get_date_end(query_parameters)

    if date_start is None:
        date_start = "static"

    metadata.update({"entry_start_date": date_start})

    if date_end is None:
        metadata.update({"entry_end_date": date_start})
    else:
        metadata.update({"entry_end_date": date_end})

    return metadata


def get_date_start(options):
    """
    Get the date_start option from the options dict.
    This gets either start_time or date_start to be backward compatible with old names.

    Parameters:
        options:    A dict containing parameters to get_gridded_data.

    Returns:
        The value of the options as either a string or a datetime object from the dict.
    """
    result = options.get("date_start", None)
    result = options.get("start_date", None) if result is None else result
    result = options.get("start_time", None) if result is None else result
    return result


def get_date_end(options):
    """
    Get the date_end option from the options dict.
    This gets either end_time or date_end to be backward compatible with old names.

    Parameters:
        options:    A dict containing parameters to get_gridded_data.

    Returns:
        The value of the options as either a string or a datetime object from the dict.
    """
    result = options.get("date_end", None)
    result = options.get("end_date", None) if result is None else result
    result = options.get("end_time", None) if result is None else result
    return result
